# This is a basic workflow to help you get started with Actions

name: TweakBuild

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: theos env
        run: |
          git clone https://github.com/xybp888/iOS-SDKs ../iOS-SDKs
          cp -r ../iOS-SDKs/iPhoneOS14.4.sdk .
          git clone https://github.com/iCH3F/iOS-13.3-Private-SDK ../iOS-13.3-Private-SDK
          mkdir -p ./iPhoneOS14.4.sdk/System/Library/PrivateFrameworks/ControlCenterUIKit.framework/Headers
          cp ../iOS-13.3-Private-SDK/iPhoneOS13.3.sdk/System/Library/PrivateFrameworks/ControlCenterUIKit.framework/Headers/* ./iPhoneOS14.4.sdk/System/Library/PrivateFrameworks/ControlCenterUIKit.framework/Headers
          git clone --recursive git://github.com/theos/theos.git ../theos
          cp ../theos/Prefix.pch .
          git clone https://github.com/Muirey03/RemoteLog.git ../RemoteLog
          cp ../RemoteLog/RemoteLog.h .
          
      - name: Add & Commit
        # You may pin to the exact commit or the version.
        # uses: EndBug/add-and-commit@2bdc0a61a03738a1d1bda24d566ad0dbe3083d87
        uses: EndBug/add-and-commit@v7.2.1
        with:
          # Arguments for the git add command
          add: .
